// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/umputun/ralphex/pkg/status"
)

// InputCollectorMock is a mock implementation of processor.InputCollector.
//
//	func TestSomethingThatUsesInputCollector(t *testing.T) {
//
//		// make and configure a mocked processor.InputCollector
//		mockedInputCollector := &InputCollectorMock{
//			AskDraftReviewFunc: func(ctx context.Context, question string, planContent string) (string, string, error) {
//				panic("mock out the AskDraftReview method")
//			},
//			AskQuestionFunc: func(ctx context.Context, question string, options []string) (string, error) {
//				panic("mock out the AskQuestion method")
//			},
//			AskConflictResolutionFunc: func(ctx context.Context, topic string, proposerArg string, reviewerArg string, options []string) (string, error) {
//				panic("mock out the AskConflictResolution method")
//			},
//			AskSectionApprovalFunc: func(ctx context.Context, sections []status.DeepPlanSectionChoice) ([]status.DeepPlanSectionChoice, error) {
//				panic("mock out the AskSectionApproval method")
//			},
//			AskDeepPlanResumeFunc: func(ctx context.Context, stateInfo string) (bool, error) {
//				panic("mock out the AskDeepPlanResume method")
//			},
//		}
//
//		// use mockedInputCollector in code that requires processor.InputCollector
//		// and then make assertions.
//
//	}
type InputCollectorMock struct {
	// AskDraftReviewFunc mocks the AskDraftReview method.
	AskDraftReviewFunc func(ctx context.Context, question string, planContent string) (string, string, error)

	// AskQuestionFunc mocks the AskQuestion method.
	AskQuestionFunc func(ctx context.Context, question string, options []string) (string, error)

	// AskConflictResolutionFunc mocks the AskConflictResolution method.
	AskConflictResolutionFunc func(ctx context.Context, topic string, proposerArg string, reviewerArg string, options []string) (string, error)

	// AskSectionApprovalFunc mocks the AskSectionApproval method.
	AskSectionApprovalFunc func(ctx context.Context, sections []status.DeepPlanSectionChoice) ([]status.DeepPlanSectionChoice, error)

	// AskDeepPlanResumeFunc mocks the AskDeepPlanResume method.
	AskDeepPlanResumeFunc func(ctx context.Context, stateInfo string) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// AskDraftReview holds details about calls to the AskDraftReview method.
		AskDraftReview []struct {
			Ctx         context.Context
			Question    string
			PlanContent string
		}
		// AskQuestion holds details about calls to the AskQuestion method.
		AskQuestion []struct {
			Ctx      context.Context
			Question string
			Options  []string
		}
		// AskConflictResolution holds details about calls to the AskConflictResolution method.
		AskConflictResolution []struct {
			Ctx         context.Context
			Topic       string
			ProposerArg string
			ReviewerArg string
			Options     []string
		}
		// AskSectionApproval holds details about calls to the AskSectionApproval method.
		AskSectionApproval []struct {
			Ctx      context.Context
			Sections []status.DeepPlanSectionChoice
		}
		// AskDeepPlanResume holds details about calls to the AskDeepPlanResume method.
		AskDeepPlanResume []struct {
			Ctx       context.Context
			StateInfo string
		}
	}
	lockAskDraftReview        sync.RWMutex
	lockAskQuestion           sync.RWMutex
	lockAskConflictResolution sync.RWMutex
	lockAskSectionApproval    sync.RWMutex
	lockAskDeepPlanResume     sync.RWMutex
}

// AskDraftReview calls AskDraftReviewFunc.
func (mock *InputCollectorMock) AskDraftReview(ctx context.Context, question string, planContent string) (string, string, error) {
	if mock.AskDraftReviewFunc == nil {
		panic("InputCollectorMock.AskDraftReviewFunc: method is nil but InputCollector.AskDraftReview was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Question    string
		PlanContent string
	}{
		Ctx:         ctx,
		Question:    question,
		PlanContent: planContent,
	}
	mock.lockAskDraftReview.Lock()
	mock.calls.AskDraftReview = append(mock.calls.AskDraftReview, callInfo)
	mock.lockAskDraftReview.Unlock()
	return mock.AskDraftReviewFunc(ctx, question, planContent)
}

// AskDraftReviewCalls gets all the calls that were made to AskDraftReview.
func (mock *InputCollectorMock) AskDraftReviewCalls() []struct {
	Ctx         context.Context
	Question    string
	PlanContent string
} {
	var calls []struct {
		Ctx         context.Context
		Question    string
		PlanContent string
	}
	mock.lockAskDraftReview.RLock()
	calls = mock.calls.AskDraftReview
	mock.lockAskDraftReview.RUnlock()
	return calls
}

// AskQuestion calls AskQuestionFunc.
func (mock *InputCollectorMock) AskQuestion(ctx context.Context, question string, options []string) (string, error) {
	if mock.AskQuestionFunc == nil {
		panic("InputCollectorMock.AskQuestionFunc: method is nil but InputCollector.AskQuestion was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Question string
		Options  []string
	}{
		Ctx:      ctx,
		Question: question,
		Options:  options,
	}
	mock.lockAskQuestion.Lock()
	mock.calls.AskQuestion = append(mock.calls.AskQuestion, callInfo)
	mock.lockAskQuestion.Unlock()
	return mock.AskQuestionFunc(ctx, question, options)
}

// AskQuestionCalls gets all the calls that were made to AskQuestion.
func (mock *InputCollectorMock) AskQuestionCalls() []struct {
	Ctx      context.Context
	Question string
	Options  []string
} {
	var calls []struct {
		Ctx      context.Context
		Question string
		Options  []string
	}
	mock.lockAskQuestion.RLock()
	calls = mock.calls.AskQuestion
	mock.lockAskQuestion.RUnlock()
	return calls
}

// AskConflictResolution calls AskConflictResolutionFunc.
func (mock *InputCollectorMock) AskConflictResolution(ctx context.Context, topic, proposerArg, reviewerArg string, options []string) (string, error) {
	if mock.AskConflictResolutionFunc == nil {
		panic("InputCollectorMock.AskConflictResolutionFunc: method is nil but InputCollector.AskConflictResolution was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Topic       string
		ProposerArg string
		ReviewerArg string
		Options     []string
	}{
		Ctx:         ctx,
		Topic:       topic,
		ProposerArg: proposerArg,
		ReviewerArg: reviewerArg,
		Options:     options,
	}
	mock.lockAskConflictResolution.Lock()
	mock.calls.AskConflictResolution = append(mock.calls.AskConflictResolution, callInfo)
	mock.lockAskConflictResolution.Unlock()
	return mock.AskConflictResolutionFunc(ctx, topic, proposerArg, reviewerArg, options)
}

// AskConflictResolutionCalls gets all the calls that were made to AskConflictResolution.
func (mock *InputCollectorMock) AskConflictResolutionCalls() []struct {
	Ctx         context.Context
	Topic       string
	ProposerArg string
	ReviewerArg string
	Options     []string
} {
	var calls []struct {
		Ctx         context.Context
		Topic       string
		ProposerArg string
		ReviewerArg string
		Options     []string
	}
	mock.lockAskConflictResolution.RLock()
	calls = mock.calls.AskConflictResolution
	mock.lockAskConflictResolution.RUnlock()
	return calls
}

// AskSectionApproval calls AskSectionApprovalFunc.
func (mock *InputCollectorMock) AskSectionApproval(ctx context.Context, sections []status.DeepPlanSectionChoice) ([]status.DeepPlanSectionChoice, error) {
	if mock.AskSectionApprovalFunc == nil {
		panic("InputCollectorMock.AskSectionApprovalFunc: method is nil but InputCollector.AskSectionApproval was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Sections []status.DeepPlanSectionChoice
	}{
		Ctx:      ctx,
		Sections: sections,
	}
	mock.lockAskSectionApproval.Lock()
	mock.calls.AskSectionApproval = append(mock.calls.AskSectionApproval, callInfo)
	mock.lockAskSectionApproval.Unlock()
	return mock.AskSectionApprovalFunc(ctx, sections)
}

// AskSectionApprovalCalls gets all the calls that were made to AskSectionApproval.
func (mock *InputCollectorMock) AskSectionApprovalCalls() []struct {
	Ctx      context.Context
	Sections []status.DeepPlanSectionChoice
} {
	var calls []struct {
		Ctx      context.Context
		Sections []status.DeepPlanSectionChoice
	}
	mock.lockAskSectionApproval.RLock()
	calls = mock.calls.AskSectionApproval
	mock.lockAskSectionApproval.RUnlock()
	return calls
}

// AskDeepPlanResume calls AskDeepPlanResumeFunc.
func (mock *InputCollectorMock) AskDeepPlanResume(ctx context.Context, stateInfo string) (bool, error) {
	if mock.AskDeepPlanResumeFunc == nil {
		panic("InputCollectorMock.AskDeepPlanResumeFunc: method is nil but InputCollector.AskDeepPlanResume was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		StateInfo string
	}{
		Ctx:       ctx,
		StateInfo: stateInfo,
	}
	mock.lockAskDeepPlanResume.Lock()
	mock.calls.AskDeepPlanResume = append(mock.calls.AskDeepPlanResume, callInfo)
	mock.lockAskDeepPlanResume.Unlock()
	return mock.AskDeepPlanResumeFunc(ctx, stateInfo)
}

// AskDeepPlanResumeCalls gets all the calls that were made to AskDeepPlanResume.
func (mock *InputCollectorMock) AskDeepPlanResumeCalls() []struct {
	Ctx       context.Context
	StateInfo string
} {
	var calls []struct {
		Ctx       context.Context
		StateInfo string
	}
	mock.lockAskDeepPlanResume.RLock()
	calls = mock.calls.AskDeepPlanResume
	mock.lockAskDeepPlanResume.RUnlock()
	return calls
}
